[features]
seeds = false
skip-lint = false

[programs.localnet]
mutual_escrow = "G46UVzSzefgfZ6Yj43XYsNTxWYv6b3RVySt9CsYtm3mx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
